controllers/CalendarController.php
<?php

namespace app\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use app\models\{
    Business, BusinessHasSpeaker, ObjectFile, Speaker
};
use yii\web\Response;

/**
 * Class CalendarController
 * @package app\controllers
 */
class CalendarController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $search_model = new Business();
        $search_model->start_date = 'upcoming';

        $q = Business::find()->alias('b')->where([
            'b.type' => [
                Business::TYPE_CALENDAR,
                Business::TYPE_BOTH,
            ],
            'b.status' => Business::STATUS_ACTIVE,
        ]);

        if ($search_model->load(Yii::$app->getRequest()->get())) {
            if ((int)$search_model->type) {
                //$q->andWhere(['b.type' => $search_model->type]);
            }
        }

        if ($search_model->start_date == 'upcoming') {
            $d = new \DateTime();
            $q->andWhere([
                '>',
                'b.start_date',
                $d->format('Y-m-d'),
            ]);
        } elseif ($search_model->start_date) {
            $d = new \DateTime($search_model->start_date);
            $q->andWhere([
                'between',
                'b.start_date',
                $d->modify('first day of this month')->format('Y-m-d'),
                $d->modify('last day of this month')->format('Y-m-d'),
            ]);
        }

        if ((int)$search_model->conference_type) {
            $q->andWhere([
                'b.conference_type' => $search_model->conference_type,
            ]);
        }

        if ((int)$search_model->speaker_id) {
            $q->leftJoin(['bhs' => BusinessHasSpeaker::tableName()], 'b.id = bhs.business_id')->andWhere([
                'bhs.speaker_id' => $search_model->speaker_id,
            ]);
        }

        $q->orderBy(['start_date' => SORT_ASC]);

        $dp = new ActiveDataProvider([
            'query' => $q,
            'pagination' => false,
        ]);
        $speakers = Speaker::find()->where(['status' => Speaker::STATUS_ACTIVE])->orderBy(['full_name' => SORT_ASC])->all();
        $dates = Business::find()
            ->select([
                'DATE_FORMAT(start_date, \'%Y-%m-%d\') start_date',
            ])
            ->where([
                'type' => [
                    Business::TYPE_CALENDAR,
                    Business::TYPE_BOTH,
                ],
                'status' => Business::STATUS_ACTIVE,
            ])
            ->groupBy(new Expression('DATE_FORMAT(start_date, \'%Y-%m\')'))
            ->orderBy(['start_date' => SORT_DESC])
            ->column();

        if (Yii::$app->getRequest()->getIsAjax()) {
            return $this->renderAjax('index', [
                'search_model' => $search_model,
                'dp' => $dp,
                'dates' => $dates,
                'speakers' => ArrayHelper::map($speakers, 'id', 'full_name'),
            ]);
        }

        return $this->render('index', [
            'search_model' => $search_model,
            'dp' => $dp,
            'dates' => $dates,
            'speakers' => ArrayHelper::map($speakers, 'id', 'full_name'),
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionView($id)
    {
        $model = Business::getActive($id);
        $models = [];

        if ($prev = Business::find()
            ->where(['<', 'start_date', "$model->start_date"])
            ->andWhere([
                'type' => [Business::TYPE_CALENDAR, Business::TYPE_BOTH],
                'status' => Business::STATUS_ACTIVE,
            ])
            ->orderBy(['start_date' => SORT_DESC])->one()
        ) {
            $models['prev'] = $prev;
        }
        if ($next = Business::find()
            ->where(['>', 'start_date', "$model->start_date"])
            ->andWhere([
                'type' => [Business::TYPE_CALENDAR, Business::TYPE_BOTH],
                'status' => Business::STATUS_ACTIVE,
            ])
            ->orderBy(['start_date' => SORT_ASC])->one()
        ) {
            $models['next'] = $next;
        }

        return $this->render('/event/view', [
            'model' => $model,
            'models' => $models,
        ]);
    }

    /**
     * Exports all Business data in json format
     * @return array
     */
    public function actionExport()
    {
        Yii::$app->getResponse()->format = Response::FORMAT_JSON;
        $models = Business::find()->orderBy(['start_date' => SORT_ASC])->all();

        $calendars_data = [];

        foreach ($models as $i => $model) {
            $speakers_data = [];
            $image_url = null;

            if ($path = ObjectFile::getAssetPath($model, 'image', true)) {
                $image_url = $path;
            }

            foreach ($model->getSpeakers() as $k => $speaker) {
                $speakers_data[$k]['attributes'] = $speaker->attributes;
                $speakers_data[$k]['image_url'] = null;

                if ($path = ObjectFile::getAssetPath($speaker, 'image', true)) {
                    $speakers_data[$k]['image_url'] = $path;
                }
            }

            $calendars_data[$i]['attributes'] = $model->attributes;
            $calendars_data[$i]['image_url'] = $image_url;
            $calendars_data[$i]['speakers_data'] = $speakers_data;
        }

        return $calendars_data;
    }
}

views/calendar/_list_item.php
<?php

/**
 * @var $this yii\web\View
 * @var $model Business
 */

use yii\helpers\Url;
use app\models\Business;
use app\models\ObjectFile;

$fmt = Yii::$app->getFormatter();
$fmt->defaultTimeZone = $fmt->timeZone;
$speakers = $model->getSpeakers();
$f_speaker = sizeof($speakers) ? $speakers[0] : null;
$css_cls = $model->conference_type == Business::SEMINAR ? 'sem' : 'web';
$str_date = !empty($model->start_date_text)
    ? $model->start_date_text
    : $fmt->asDate($model->start_date, 'long');
$url = Url::to(['/calendar/view', 'id' => $model->id]);
if(!$model->button_text && !$model->button_url && $model->conference_type == Business::SEMINAR) {
    $url = Url::to(['/event/view', 'id' => $model->id]);
}
?>
<div class="col-sm-3 col-xs-12">
    <!-- item start -->
    <div class="b-calendar__item-web b-calendar__item">
        <div class="b-calendar__item-<?= $css_cls ?>-title"><?= Business::$conference_types[$model->conference_type] ?></div>

        <div class="b-calendar__item-web-date"><?= $str_date ?></div>

        <div class="b-calendar__item-<?= $css_cls ?>-subtitle">
            <a data-pjax="0" href="<?= $url ?>"><?= $model->title ?></a>
        </div>

        <?php if (date('H:i', strtotime($model->start_date)) != '00:00') { ?>
            <!-- date -->
            <div class="b-calendar__item-web-time"><?= date('H:i', strtotime($model->start_date)) ?></div>
        <?php } ?>

        <?php if (!empty($model->city_name) ) { ?>
            <div class="b-calendar__item-sem-town"><?= $model->city_name ?></div>
        <?php } ?>

        <?php if ($model->button_text && $model->button_url) { ?>
            <div class="b-calendar__item-sem-btn">
                <a data-pjax="0" class="b-button-green" href="<?= $model->button_url ?>"><?= $model->button_text ?></a>
            </div>
        <?php } else if($model->conference_type == Business::SEMINAR) { ?>
            <div class="b-calendar__item-sem-btn">
                <a data-pjax="0" class="b-button-green" href="<?= $url ?>">
                    <?= Yii::t('labels', 'Watch program') ?>
                </a>
            </div>
       <?php } ?>

        <hr>

        <?php if (sizeof($speakers)) { ?>
            <table class="b-calendar__item-web-speaker">
                <tbody>
                <tr>
                    <td>
                        <?php if ($path = ObjectFile::getAssetPath($f_speaker, 'image', true)) { ?>
                            <div class="b-calendar__item-web-speaker-ava">
                                <img height="60" src="<?= $path ?>" alt="">
                            </div>
                        <?php } ?>
                    </td>
                    <td>
                        <div class="b-calendar__item-web-speaker-name"><?= $f_speaker->full_name ?></div>
                        <div class="b-calendar__item-web-speaker-info"><?= Yii::t('labels', 'Speaker') ?></div>
                    </td>
                </tr>
                </tbody>
            </table>
        <?php } ?>
    </div>
    <!-- item end -->
</div>

views/calendar/index.php
<?php
/**
 * @var $this \yii\web\View
 * @var $search_model Business
 * @var $dp \yii\data\ActiveDataProvider
 * @var $speakers array
 * @var $dates array
 */

use yii\widgets\{
    Pjax,
    ListView
};
use yii\helpers\{
    Url,
    Html
};
use app\helpers\H;
use app\assets\AppAsset;
use app\models\Business;

$this->title = 'Календарь мероприятий';
$this->registerJsFile(Yii::getAlias('@web/js/calendar-list-actions.js'), [
    'depends' => [AppAsset::class]
]);
$fmt = Yii::$app->getFormatter();
$fmt->defaultTimeZone = $fmt->timeZone;

$active_start_date = empty($search_model->start_date)
    ? Yii::t('labels', 'All period')
    : ($search_model->start_date == 'upcoming'
        ? Yii::t('labels', 'Current')
        : H::mb_ucfirst($fmt->asDate($search_model->start_date, 'LLLL Y')));

$active_type = empty($search_model->type)
    ? Yii::t('labels', 'All subjects')
    : ([
            1 => Yii::t('labels', 'Business'),
            2 => Yii::t('labels', 'Product'),
        ][$search_model->type] ?? "");

$active_speaker_id = empty($search_model->speaker_id)
    ? Yii::t('labels', 'All speakers')
    : ($speakers[$search_model->speaker_id] ?? "");

$active_conference_type = empty($search_model->conference_type)
    ? Yii::t('labels', 'All types')
    : (Business::$conference_types[$search_model->type] ?? "");

?>
<div class="b-calendar">
    <div class="row">
        <div class="col-xs-12">
            <div class="b-breadcrumbs">
                <ul>
                    <li><a href="/">Главная</a></li>
                    <li><?= $this->title ?></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="b-calendar__title"><?= $this->title ?></div>
        </div>
    </div>

    <div class="row">
        <div class="b-sorting-calendar">
            <form id="calendar-form" action="<?= Url::to(['/calendar/index']) ?>">
                <div class="row">

                    <div class="col-sm-3 col-xs-12">
                        <div class="sort sort-dropdown-input">
                            <label for="" class="sort-calendar__label">
                                <?= Yii::t('labels', 'Period') ?>
                                <ul class="sort__select">
                                    <li>
                                        <a class="active" href="javascript://"><?= $active_start_date ?></a>
                                        <ul class="sort__select-drop">
                                            <li><a data-value="upcoming"
                                                   href="javascript://"><?= Yii::t('labels', 'Current') ?></a></li>
                                            <li><a data-value=""
                                                   href="javascript://"><?= Yii::t('labels', 'All period') ?></a>
                                            </li>
                                            <li class="disabled">
                                                <span><?= Yii::t('labels', 'Archive') ?></span>
                                                <hr>
                                            </li>

                                            <?php foreach ($dates as $date) { ?>
                                                <li><a data-value="<?= $date ?>" href="javascript://">
                                                        <?= H::mb_ucfirst($fmt->asDate($date, 'LLLL Y')) ?>
                                                    </a></li>
                                            <?php } ?>

                                        </ul>
                                    </li>
                                </ul>
                            </label>
                            <?= Html::activeHiddenInput($search_model, 'start_date', [
                                'class' => 'sort__input-selected',
                            ]) ?>
                        </div>
                    </div>

                    <div class="col-sm-3 col-xs-12">
                        <div class="sort sort-dropdown-input">
                            <label for="" class="sort-calendar__label">
                                <?= Yii::t('labels', 'Subjects') ?>
                                <ul class="sort__select">
                                    <li>
                                        <a class="active" href="javascript://"><?= $active_type ?></a>
                                        <ul class="sort__select-drop">
                                            <li><a data-value=""
                                                   href="javascript://"><?= Yii::t('labels', 'All subjects') ?></a>
                                            </li>
                                            <li><a data-value="1"
                                                   href="javascript://"><?= Yii::t('labels', 'Business') ?></a></li>
                                            <li><a data-value="2"
                                                   href="javascript://"><?= Yii::t('labels', 'Product') ?></a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </label>
                            <?= Html::activeHiddenInput($search_model, 'type', [
                                'class' => 'sort__input-selected',
                            ]) ?>
                        </div>
                    </div>

                    <div class="col-sm-3 col-xs-12">
                        <div class="sort sort-dropdown-input">
                            <label for="" class="sort-calendar__label">
                                <?= Yii::t('labels', 'Speaker') ?>
                                <ul class="sort__select">
                                    <li>
                                        <a class="active" href="javascript://"><?= $active_speaker_id ?></a>
                                        <ul class="sort__select-drop">
                                            <li><a data-value=""
                                                   href="javascript://"><?= Yii::t('labels', 'All speakers') ?></a>
                                            </li>

                                            <?php foreach ($speakers as $id => $name) { ?>
                                                <li><a data-value="<?= $id ?>" href="javascript://"><?= $name ?></a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </li>
                                </ul>
                            </label>
                            <?= Html::activeHiddenInput($search_model, 'speaker_id', [
                                'class' => 'sort__input-selected',
                            ]) ?>
                        </div>
                    </div>

                    <div class="col-sm-3 col-xs-12">
                        <div class="sort sort-dropdown-input">
                            <!-- one sorting block -->
                            <label for="" class="sort-calendar__label">
                                <?= Yii::t('labels', 'Types') ?>
                                <ul class="sort__select">
                                    <li>
                                        <a class="active" href="javascript://"><?= $active_conference_type ?></a>
                                        <ul class="sort__select-drop">
                                            <li><a data-value=""
                                                   href="javascript://"> <?= Yii::t('labels', 'All types') ?></a>
                                            </li>
                                            <?php foreach (Business::$conference_types as $k => $name) { ?>
                                                <li><a data-value="<?= $k ?>" href="javascript://"><?= $name ?></a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </li>
                                </ul>
                            </label>
                            <?= Html::activeHiddenInput($search_model, 'conference_type', [
                                'class' => 'sort__input-selected',
                            ]) ?>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="b-calendar-list">
                <?php
                $cnt = $dp->getTotalCount();
                Pjax::begin(['formSelector' => '#calendar-form']);
                echo '<div class="pjax-container-loader"></div>';
                echo ListView::widget([
                    'dataProvider' => $dp,
                    'options' => [
                        'class' => 'calendar-list-view',
                    ],
                    'itemView' => '/calendar/_list_item',
                    'layout' => "{items}",
                    'itemOptions' => [
                        'tag' => false,
                    ],
                    'beforeItem' => function ($model, $key, $index) use ($cnt) {
                        return $index % 4 == 0 ? "<div class='row'>" : null;
                    },
                    'afterItem' => function ($model, $key, $index) use ($cnt) {
                        return ($index + 1) % 4 == 0 || $index + 1 == $cnt ? "</div>" : null;
                    },
                ]);
                Pjax::end();
                ?>
            </div>
        </div>
    </div>

</div>