models/Promotion.php
<?php

namespace app\models;

use app\behaviors\TranslationBehavior;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\db\Schema;
use app\helpers\AR;

/**
 * This is the model class for table "promotion".
 *
 * @property int $id
 * @property int $image_id
 * @property int $product_id
 * @property string $title
 * @property string $description
 * @property string $sub_description
 * @property int $status
 * @property string $start_date
 * @property string $end_date
 * @property string $created_at
 * @property string $updated_at
 */
class Promotion extends AR
{
    /**
     * @return array
     */
    public function attributeTypes()
    {
        return [
            'id' => Schema::TYPE_PK,
            'image_id' => Schema::TYPE_INTEGER,
            'product_id' => Schema::TYPE_INTEGER,
            'title' => Schema::TYPE_STRING,
            'description' => Schema::TYPE_TEXT,
            'sub_description' => Schema::TYPE_TEXT,
            'start_date' => Schema::TYPE_DATETIME,
            'end_date' => Schema::TYPE_DATETIME,
            'status' => Schema::TYPE_INTEGER,
            'updated_at' => Schema::TYPE_TIMESTAMP,
            'created_at' => Schema::TYPE_TIMESTAMP,
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'promotion';
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'translation' => [
                'class' => TranslationBehavior::class,
                'default_language' => YII_DEFAULT_LANGUAGE
            ],
            'timestamp' => [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => 'updated_at'
                ],
                'value' => new Expression('now()')
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'description', 'start_date', 'end_date', 'sub_description'], 'string'],
            [['product_id', 'status'], 'safe'],
            [['start_date'], 'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Продукт',
            'image_id' => 'Изображение',
            'title' => 'Заголовок',
            'description' => 'Описание',
            'sub_description' => 'Сокращенное описание',
            'start_date' => 'Дата старта',
            'end_date' => 'Дата окончания',
            'status' => 'Статус',
            'created_at' => 'Создан',
            'updated_at' => 'Обновлен',
        ];
    }

    /**
     * @return ObjectFile
     */
    public function getImage()
    {
        /** @var ObjectFile $o */
        if ($o = $this->hasOne(ObjectFile::class, ['id' => 'image_id'])->one()) {
            $o->setOwnerId($this->id);
        }

        return $o;
    }
}

controllers/PromotionController.php
<?php

namespace app\controllers;

use yii\data\ActiveDataProvider;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use app\models\Promotion;

/**
 * Class PromotionController
 * @package app\controllers
 */
class PromotionController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Promotion::find()
                ->where(['<=', 'start_date', date('Y:m:d H:i:s')])
                ->andWhere(['>=', 'end_date', date('Y:m:d')])
                ->andWhere(['status' => Promotion::STATUS_ACTIVE])
        ]);

        return $this->render('index', ['dataProvider' => $dataProvider]);
    }

    /**
     * @param $id
     * @return string|\yii\web\Response
     * @throws BadRequestHttpException
     */
    public function actionView($id)
    {
        if (!$id) {
            throw new BadRequestHttpException('Неверный адрес.');
        }

        if (!$model = Promotion::findOne($id)) {
            return $this->redirect(['/site']);
        }

        return $this->render('view', ['model' => $model]);
    }
}

views/promotion/_list_item.php
<?php
/**
 * @var $this yii\web\View
 * @var Promotion $model
 */

use \yii\helpers\Url;
use \app\models\Promotion;
use \app\models\ObjectFile;

$this->title = $model->title;
$fmt = Yii::$app->getFormatter();
$fmt->defaultTimeZone = $fmt->timeZone;
$path = ObjectFile::getAssetPath($model, 'image', true);
?>
<div class="col-sm-4 col-xs-12">
    <div class="b-promo-list__item active">
        <a href="<?= Url::to(['/promotion/view', 'id' => $model->id]) ?>" class="b-promo-list__img"><img
                    src="<?= $path ?>" alt=""></a>
        <div class="b-promo-list__date"><?= $fmt->asDate($model->start_date, 'long') ?></div>
        <div class="b-promo-list__subtitle"><?= $model->title ?></div>
        <p class="b-promo-list__text"><?= $model->sub_description ?></p>
    </div>
</div>

views/promotion/index.php
<?php
/**
 * @var $this yii\web\View
 * @var $dataProvider \yii\data\ActiveDataProvider
 */

use yii\widgets\ListView;

$this->title = Yii::t('layout', 'Promotions');
?>
<div class="b-descr-page b-descr-page-for-promo-list">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <!-- substrate background : begin -->
                <div class="b-descr-page__substrate-bg">
                    <div class="b-descr-page-substrate-bg">
                        <!-- title -->
                        <div class="b-descr-page__title"><?= Yii::t('layout', 'Promotions') ?></div>
                        <!-- description -->
                        <p class="b-descr-page__text">
                            <?= Yii::t('layout', 'To our range of products, we treat carefully and consciously, since we ourselves use it. We recommend everyone, at a minimum, to introduce into their diet natural foods that do not contain GMOs, preservatives and a variety of food chemical compounds.') ?>
                        </p>
                    </div>
                </div>
                <!-- substrate background : end -->
            </div>
        </div>
    </div>
</div>

<div class="b-promo-list">
    <div class="container">
        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'options' => [
                'class' => 'row',
            ],
            'itemView' => '/promotion/_list_item',
            'layout' => "{items}",
            'itemOptions' => [
                'tag' => false,
            ],
        ]) ?>
    </div>
</div>

views/promotion/view.php
<?php
/**
 * @var $model Promotion
 */

use yii\helpers\Url;
use app\models\Promotion;
use app\models\ObjectFile;

$fmt = Yii::$app->getFormatter();
$fmt->defaultTimeZone = $fmt->timeZone;
$path = ObjectFile::getAssetPath($model, 'image', true);

?>
<div class="b-card-promo-typical">
    <!-- description page : begin -->
    <div class="b-descr-page b-descr-page-for-card-promo-typical">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <!-- substrate background : begin -->
                    <div class="b-descr-page__substrate-bg">
                        <div class="b-descr-page-substrate-bg-typical">
                            <!-- <p class="b-descr-page-promo-typical__text_top">Партнерская программа</p> -->
                            <!-- title -->
                            <div class="b-descr-page-promo-typical__title"><?= $model->title ?></div>
                            <!-- description -->

                            <!-- options : begin -->
                            <div class="b-descr-page__options">
                                <!-- date -->
                                <div class="b-descr-page__date"><?= date("Y-m-d", strtotime($model->start_date)) ?></div>
                                <!-- events -->
                                <div class="b-descr-page__events">Акция</div>
                                <div class="b-descr-page__share"></div>
                            </div>
                            <!-- options : end -->
                        </div>
                    </div>
                    <!-- substrate background : end -->
                </div>
            </div>
            <!-- banner : begin -->
            <div class="b-descr-page__banner">
                <img src="<?= $path ?>" alt="">
            </div>
            <!-- banner : end -->
        </div>
    </div>
    <!-- description page : end -->
    <!-- advantages : begin -->
    <div class="b-card-promo-typical__advantages">
        <div class="container">
            <div class="row">
                <?= htmlspecialchars_decode($model->description) ?>
                <div class="row horizontal-nav-soc">
                    <div class="col-sm-6 col-xs-12">
                        <ul>
                            <li class="fa fa-tags"></li>
                            <li>Акции</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- advantages : end -->
    </div>
    <!-- CARD PROMO : end -->
</div>